### ISSUE TITLE
Couldn't open file! invalid compression method

### ISSUE THREAD

**Issue by SpiritQuaddicted** [hrehfeld/QuakeInjector#146]
Trying to install https://www.quaddicted.com/reviews/qbj_1.05.html the Injector fails to uncompress the ZIP archive and shows the user a message "`Couldn't open file! invalid compression method`".

No idea what might be wrong there. The file is "compressed" with "store" but I would assume that other files in the archive were using that "compression" already and I am not aware of issues.

https://www.quaddicted.com/filebase/qbj_1.05.zip

md5: 601bc9baa2b4226d101f16cb8cb45b65

```
ctsj2.zip:                 Zip archive data, at least v2.0 to extract, compression method=deflate
qbj_1.05.zip:              Zip archive data, at least v2.0 to extract, compression method=store
```

**Comment by SpiritQuaddicted** [comment]
I unpacked and packed it again with a simple "zip -r qbj_1.05.zip.zip qbj" and the resulting archive works fine.

However I noticed that my compressed version is about the same size (512MB) as the supposedly uncompressed "store" version (480MB). An actually uncompressed ZIP is at 1.5GB.

It seems like the algorithm in the file's metadata might be mislabeled as "store" when it is actually compressed?

**Comment by SpiritQuaddicted** [comment]
Yeah, `file` is wrong. `unzip -v 1qbj_1.05.zip` shows that files a compressed with "`Def64N`".

**Comment by neogeographica** [comment]
Yeah I ran into this problem myself. It happens for large zipfiles but also apparently for smaller zipfiles that have been incrementally updated: https://github.com/neogeographica/quakestarter/issues/84

In my case I was using a .NET assembly to do the unzip but it looks like java.util.Zip has the same problem.

Just unzipping and rezipping fixes the issue if the file isn't super large (I forget the threshold there). Don't know of a better solution unfortunately... maybe there's at least some automated way to scan a zipfile for this.

**Comment by SpiritQuaddicted** [comment]
Argh... :(

https://stackoverflow.com/questions/34299045/java-compression-library-to-support-deflate64 suggests using https://commons.apache.org/proper/commons-compress/

**Comment by SpiritQuaddicted** [comment]
`dtintin_fixed.zip` is another one.

**Comment by johnnycz** [comment]
Fixed: https://github.com/johnnycz/QuakeInjector/tree/issue-146-invalid-compression-method

**Comment by SpiritQuaddicted** [comment]
Dang, I forgot about this. Would have been a nice addition to the alpha07.

Could you make a pull request so that we get it in alpha08?

Thanks a lot for fixing this!

**Comment by johnnycz** [comment]
Yeah, this is still on my radar. I think the alpha08 could be made of this + the repackaging support (once finished). Those two updates make sense together as they are the same theme - making more packages compatible.

**Comment by xxvertigoxx** [comment]
I know this project is old but I think it's worth releasing the fix as the issue persists.

**Comment by SpiritQuaddicted** [comment]
https://discuss.quaddicted.com/t/quake-injector-version-8-release-candidate-2/8138
